flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.5.0.0
- QuickCheck-2.9.2
- ansi-terminal-0.6.2.3
- async-2.1.1
- call-stack-0.1.0
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- primitive-0.6.2.0
- quickcheck-io-0.1.4
- random-1.1
- setenv-0.1.1.3
- stm-2.4.4.1
- tf-random-0.5
resolver: ghc-8.0.1
